# Generated by Django 5.0.1 on 2024-01-06 08:38

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default=None, upload_to=books.models.upload_image_path),
            preserve_default=False,
        ),
    ]
